### ISSUE TITLE
Add option for port

### ISSUE THREAD

**Issue by markhowellsmead** [SayHelloGmbH/wp-rsync#10]
Some hostings require that you specify a custom port (e.g. Hostpoint is 2121).

**Comment by nico-martin** [comment]
Very good point! I'll add that as soon as possible.

**Comment by nico-martin** [comment]
For now you could use the built in filter `wprsync_excludes`. I built it to add include/exclude arguments. But you could also try to add an -e. I have not tried it yet but I think it should work:

```php
add_filter( 'wprsync_excludes', function( $args ){
  $args[] = '-e "ssh -p 2121"';
  return $args;
});
```

**Comment by markhowellsmead** [comment]
No hurry but thanks for the suggestion :)

**Comment by nico-martin** [comment]
I added a new option to overwrite the ssh port number.
